# see: https://api.vibemap.com/v0.2/swagger/

routes: 
    discover:
        # Place types of either 'places' or 'events'
        ':placeType/:id':
            params:
                id: String
        
        params: 
            activity: Array
            days: Integer
            latitude: Float
            longitude: Float
            searchTerm: String
            zoom: Float
            vibe: Array
    guides: 
        params: 
            id: String
            
            