# see: https://api.vibemap.com/v0.2/swagger/

routes: 
    explore:
        params: 
            activity: Array
            days: Integer
            latitude: Float
            longitude: Float
            search: String
            zoom: Float
            vibe: Array
    place: 
        params: 
            id: String
    event: 
        params:
            id: String
    guide: 
        params: 
            id: String
                
            